name: Cloud-PC-Fast
on:
  workflow_dispatch:
    inputs:
      crd_code:
        description: 'Вставь ТОЛЬКО код (auth code)'
        required: true
      crd_pin:
        description: 'PIN (минимум 6 цифр)'
        required: true
        default: '123456'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 1. Установка CRD и Discord
      run: |
        # Ставим CRD быстро
        $crdUrl = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
        Invoke-WebRequest -Uri $crdUrl -OutFile "crd.msi"
        Start-Process msiexec.exe -ArgumentList "/i crd.msi /qn" -Wait
        
        # Качаем Discord (установка будет позже в фоне)
        $discordUrl = "https://discord.com/api/download?platform=win"
        Invoke-WebRequest -Uri $discordUrl -OutFile "DiscordSetup.exe"

    - name: 2. Мгновенный запуск Хоста
      shell: pwsh
      run: |
        # Запускаем сразу, чтобы код не протух
        & "${Env:ProgramFiles(x86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" `
        --code="${{ github.event.inputs.crd_code }}" `
        --redirect-url="https://remotedesktop.google.com/_/oauthredirect" `
        --name=$Env:COMPUTERNAME `
        --pin=${{ github.event.inputs.crd_pin }}

    - name: 3. Фоновая установка Discord и ожидание
      run: |
        # Пока ты подключаешься, ставим дискорд
        Start-Process ".\DiscordSetup.exe" -ArgumentList "--s"
        
        Write-Host "Подключайся к remotedesktop.google.com!"
        # Держим сервер включенным 6 часов
        $i = 0
        while($i -lt 360) {
          Start-Sleep -Seconds 60
          $i++
        }
