name: Cloud-PC-Custom
on:
  workflow_dispatch:
    inputs:
      crd_code:
        description: 'Вставь ТОЛЬКО код (после --code=)'
        required: true
      crd_pin:
        description: 'PIN (минимум 6 цифр)'
        required: true
        default: '123456'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Установка Chrome Remote Desktop
      run: |
        $crdUrl = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
        Invoke-WebRequest -Uri $crdUrl -OutFile "crd.msi"
        Start-Process msiexec.exe -ArgumentList "/i crd.msi /qn" -Wait

    - name: Установка Discord
      run: |
        $discordUrl = "https://discord.com/api/download?platform=win"
        Invoke-WebRequest -Uri $discordUrl -OutFile "DiscordSetup.exe"
        Start-Process ".\DiscordSetup.exe" -ArgumentList "--s" -Wait

    - name: Попытка включить звук (Virtual Audio)
      continue-on-error: true # Если опять 404, билд пойдет дальше
      run: |
        # Используем шоколати (choco) только для аудио, так как их зеркала надежнее
        choco install vb-audio-vac -y

    - name: Запуск Хоста
      shell: pwsh
      run: |
        # Запуск службы CRD с твоим кодом
        & "${Env:ProgramFiles(x86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" `
        --code="${{ github.event.inputs.crd_code }}" `
        --redirect-url="https://remotedesktop.google.com/_/oauthredirect" `
        --name=$Env:COMPUTERNAME `
        --pin=${{ github.event.inputs.crd_pin }}

    - name: Keep Alive (6 hours)
      run: |
        Write-Host "PC is ALIVE. Connect via remotedesktop.google.com"
        $i = 0
        while($i -lt 360) {
          Start-Sleep -Seconds 60
          $i++
        }
